version: '3'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "8011:5432"
  prod:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    env_file:
      - .env
    ports:
      - "8012:4000"
    command: bash -c "/app/run.sh"

