version: '3'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "8011:5432"
  prod:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DATABASE_URL=ecto://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}/${DB_DATABASE}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}
    ports:
      - "8012:4000"
    command: bash -c "/app/run.sh"

